title: Fred(Jiacong) Bao
logo: <img src="image/jiacong_bao.jpg" alt="Fred Bao" class="circular-image">
  
description: |
  **Contact**
    * Email: your.email@example.com
    * [LinkedIn](your-linkedin-url)
    * [GitHub](your-github-profile)
  
theme: jekyll-theme-minimal
