title: Jiacong (Fred) Bao
theme: jekyll-theme-minimal

description: >-
  Jiacong (Fred) Bao — PhD Candidate in Operations Management, Robert H. Smith
  School of Business, University of Maryland.
  

