title: Fred(Jiacong) Bao
logo: image/jiacong_bao.jpg
  
description: |
  **Contact**
    * Email: your.email@example.com
    * [LinkedIn](your-linkedin-url)
    * [GitHub](your-github-profile)
  
theme: jekyll-theme-minimal
