title: Fred(Jiacong) Bao
theme: jekyll-theme-minimal

logo: image/jiacong_bao.jpg
  
description: |
  <p> PhD Student in Operations Management, University of MarylanD</p>
  
  <h3>Contact</h3>
  <p><i class='fas fa-map-marker-alt'></i> College Park, Maryland</p>
  <p><i class='fas fa-envelope'></i> <a href='mailto:jcbao@umd.edu'>jcbao@umd.edu</a></p>
  <p><i class='fab fa-linkedin'></i> <a href='https://www.linkedin.com/in/fred-bao/'>LinkedIn</a></p>
  <p><i class='fas fa-graduation-cap'></i> <a href='https://scholar.google.com/citations?user=YOUR-ID'>Google Scholar</a></p>
  
theme: jekyll-theme-minimal
  

