title: Fred(Jiacong) Bao
logo: image/jiacong_bao.jpg
  
description: "<h3>Contact</h3><ul><li>Email: your.email@example.com</li><li><a href='https://linkedin.com/in/your-profile'>LinkedIn</a></li><li><a href='https://github.com/your-username'>GitHub</a></li></ul>"
  
theme: jekyll-theme-minimal
