title: Fred(Jiacong) Bao
theme: jekyll-theme-minimal

author:
  name   : "Fred(Jiacong) Bao"
  avatar : "/image/jiacong_bao.jpg"
  bio    : "PhD student in Operations Management"
  location : "Maryland, United States"
  links:
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/fred-bao/"
  

